FROM python:2.7-slim

# Installing docker CLI
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
       apt-transport-https \
       ca-certificates \
       curl \
       gnupg2 \
       software-properties-common \
 && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
 && add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable" \
 && apt-get update \
 && apt-get install -y docker-ce

ADD . /opt/DockerMakefiles
RUN pip install -r /opt/DockerMakefiles/requirements.txt
WORKDIR /opt/DockerMakefiles

